import { User } from "discord.js"
import Conversation from "../../../types/Conversation"

export default (user: User, module: string, uuid: string) => new Conversation(user,
	'Вы начали тест правил.',[
		{question: 'На каком расстоянии от постройки действует граница страны?', answerRegExp:/^\d+$/},
		{question: 'На сколько дней новые страны получают защиту от администрации?', answerRegExp:/^/},
		{question: 'Наказание за крупное разрушение на нейтральной территории?', answerRegExp:/^/},
		{question: 'Спустя какое время после объявления войны можно начинать боевые действия?', answerRegExp:/^\d+$/},
		{question: 'Места, где мародёр не может грабить и убивать?', answerRegExp:/^/},
		{question: 'Через сколько дней полного неактива среди военных страна автоматически капитулирует?', answerRegExp:/^\d+$/},
		{question: 'Два "гения" решили устроить срач в общем чате. Ваши действия?', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
		{question: '', answerRegExp:/^/},
	],
	module,
	uuid
)